---
spring:
 profiles: local
 application:
   name: gateway
 cloud:
   config:
     uri: http://localhost:8001
 rabbitmq:
   username: guest
   password: guest
   addresses: localhost
   port: 5672

---
spring:
 profiles: heroku
 application:
   name: gateway
 cloud:
   config:
     uri: https://spotlight-config-server.herokuapp.com/
 rabbitmq:
   username: guest
   password: guest
   addresses: localhost
   port: 5672
